[package]
name = "ipChecker"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.8.1"
relm4 = "0.8.1"
tracker = "0.2.1"
chrono = "0.4.34"
relm4-components = "0.8.1"
relm4-icons = "0.8.2"
rand = "0.9.0-alpha.1"
